"use client";

import "./globals.css";
import { Metadata } from "next";
import { Inter } from "next/font/google";
import Head from "./head";
import { RecoilRoot } from "recoil";
import { ThemeProvider } from "styled-components";
import { theme } from "@/styles/theme";
import StyledComponentsRegistry from "@/lib/registry";
import { QueryClientProvider, QueryClient } from "@tanstack/react-query";
import { GlobalStyle } from "@/styles/globals-style";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "🛒 ZOOLOG",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const queryClient = new QueryClient({
    defaultOptions: {
      queries: {
        retry: 1,
        refetchOnMount: true,
        refetchOnWindowFocus: true,
        staleTime: 1000 * 1000,
        cacheTime: Infinity,
      },
    },
  });

  console.log(`
  ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣀⣠⣄⡀⠀⠀⠀⣀⣠⣄⡀⠀⢀⣀⣀⠀⠀⠀⣀⣀⣤⣀⠀⠀⠀⢀⣀⣤⣄⡀⠀⠀⠀⠀⠀
  ⠀⠀⠀⠀⠀⠀⣿⣿⣿⣿⣿⣿⡇⣴⣿⣿⣿⣿⣷⠀⣠⣾⣿⣿⣿⣿⡄⣿⣿⣿⠀⢠⣴⣿⣿⣿⣿⣧⢀⣴⣿⡿⢿⣿⣿⡄⠀⠀⠀⠀
  ⠀⠀⠀⠀⠀⠀⠛⢉⣽⣿⣿⢟⣿⣿⣿⠏⠙⣿⣿⣷⣿⣿⠟⠉⣿⣿⣿⣿⣿⠇⢠⣾⣿⡿⠋⢻⣿⣿⣾⣿⡿⠁⠀⠉⠉⠀⠀⠀⠀⠀
  ⠀⠀⠀⠀⠀⠀⣠⣿⣿⣿⠋⢸⣿⣿⠁⠀⢰⣿⣿⣿⣿⠇⠀⢀⣿⣿⣿⣿⡿⠀⣿⣿⡟⠀⠀⣼⣿⣿⣿⣿⠁⣠⣤⣤⣶⠀⠀⠀⠀⠀
  ⠀⠀⠀⠀⢀⣴⣿⣿⣟⣁⣀⣿⣿⣿⢀⣠⣿⣿⢻⣿⣿⡀⣠⣾⣿⠇⣿⣿⡇⠀⣿⣿⡇⢀⣼⣿⡿⣿⣿⣿⠘⢛⣿⣿⠇⠀⠀⠀⠀⠀
  ⠀⠀⠀⠀⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠿⠁⠸⣿⣿⣿⣿⡿⠉⢰⣿⣿⣷⣶⣿⣿⣿⣿⣿⠏⠀⢻⣿⣿⣶⣾⣿⠟⠀⠀⠀⠀⠀⠀
  ⠀⠀⠀⠀⠈⠉⠁⠀⠀⠀⠀⠀⠉⠛⠉⠁⠀⠀⠀⠉⠛⠋⠁⠀⠀⠈⠉⠉⠀⠀⠈⠙⠋⠉⠀⠀⠀⠀⠙⠻⠟⠋⠁⠀⠀⠀⠀⠀⠀⠀
  ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
  ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
  ⣶⡆⣶⠶⠰⣶⠆⣶⡆⣶⣶⡶⠆⢰⣶⣦⣶⢶⡶⣶⢶⣶⡶⣦⣶⣶⣶⣴⣶⣶⣶⡶⠖⢰⣶⢰⣶⣦⣶⠀⣶⢶⣴⡆⢰⣶⣦⡶⣆⠀
  ⣿⡇⣿⠛⠀⣿⠀⣿⣿⣿⣿⡟⠃⢸⣿⡿⣿⢸⡇⣿⢿⣿⡇⣿⣿⣿⣿⣿⣿⣇⣼⡟⠃⢸⣿⣿⣿⢿⡇⠀⣿⢻⣿⡇⢸⣿⣿⡗⣷⠀
  ⠛⠛⠛⠛⠀⠛⠀⠛⠛⠛⠛⠛⠃⠘⠛⠃⠛⠘⠃⠛⠘⠛⠛⠋⠛⠋⠙⠛⠙⠛⠙⠛⠛⠘⠛⠃⠛⠘⠃⠀⠛⠛⠙⠛⠛⠛⠉⠛⠃⠀
  `);

  return (
    <html lang="ko">
      <Head />
      <QueryClientProvider client={queryClient}>
        <RecoilRoot>
          <ThemeProvider theme={theme}>
            <StyledComponentsRegistry>
              <>
                <GlobalStyle />
                <body>{children}</body>
              </>
            </StyledComponentsRegistry>
          </ThemeProvider>
        </RecoilRoot>
        <ReactQueryDevtools initialIsOpen={false} />
      </QueryClientProvider>
    </html>
  );
}
